// Generated by Pigeon from apps/mobile/pigeons/. Do not edit by hand:
// run `dart run pigeon --input pigeons/<file>.dart` in apps/mobile instead.
// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.brandtbd.sporand_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object ClipPlayerApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is NativeBridgeError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/** `round.playback_started.output_route`. */
enum class OutputRouteMessage(val raw: Int) {
  SPEAKER(0),
  WIRED(1),
  BLUETOOTH(2),
  AIRPLAY(3),
  OTHER(4);

  companion object {
    fun ofRaw(raw: Int): OutputRouteMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * One snippet of a signed clip URL (`round.prepare.clip`).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ClipSourceMessage (
  val clipUrl: String,
  /** Matches a `game.starting.prefetch[].clip_ref` already in the cache. */
  val clipRef: String? = null,
  val snippetStartMs: Long,
  val snippetDurationMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClipSourceMessage {
      val clipUrl = pigeonVar_list[0] as String
      val clipRef = pigeonVar_list[1] as String?
      val snippetStartMs = pigeonVar_list[2] as Long
      val snippetDurationMs = pigeonVar_list[3] as Long
      return ClipSourceMessage(clipUrl, clipRef, snippetStartMs, snippetDurationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clipUrl,
      clipRef,
      snippetStartMs,
      snippetDurationMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ClipSourceMessage
    return ClipPlayerApiPigeonUtils.deepEquals(this.clipUrl, other.clipUrl) && ClipPlayerApiPigeonUtils.deepEquals(this.clipRef, other.clipRef) && ClipPlayerApiPigeonUtils.deepEquals(this.snippetStartMs, other.snippetStartMs) && ClipPlayerApiPigeonUtils.deepEquals(this.snippetDurationMs, other.snippetDurationMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ClipPlayerApiPigeonUtils.deepHash(this.clipUrl)
    result = 31 * result + ClipPlayerApiPigeonUtils.deepHash(this.clipRef)
    result = 31 * result + ClipPlayerApiPigeonUtils.deepHash(this.snippetStartMs)
    result = 31 * result + ClipPlayerApiPigeonUtils.deepHash(this.snippetDurationMs)
    return result
  }
  override fun toString(): String {
    return "ClipSourceMessage(clipUrl=$clipUrl, clipRef=$clipRef, snippetStartMs=$snippetStartMs, snippetDurationMs=$snippetDurationMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreloadResultMessage (
  val ok: Boolean,
  val preloadMs: Long,
  /** snake_case failure code for `round.playback_failed.reason`. */
  val errorCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreloadResultMessage {
      val ok = pigeonVar_list[0] as Boolean
      val preloadMs = pigeonVar_list[1] as Long
      val errorCode = pigeonVar_list[2] as String?
      return PreloadResultMessage(ok, preloadMs, errorCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ok,
      preloadMs,
      errorCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PreloadResultMessage
    return ClipPlayerApiPigeonUtils.deepEquals(this.ok, other.ok) && ClipPlayerApiPigeonUtils.deepEquals(this.preloadMs, other.preloadMs) && ClipPlayerApiPigeonUtils.deepEquals(this.errorCode, other.errorCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ClipPlayerApiPigeonUtils.deepHash(this.ok)
    result = 31 * result + ClipPlayerApiPigeonUtils.deepHash(this.preloadMs)
    result = 31 * result + ClipPlayerApiPigeonUtils.deepHash(this.errorCode)
    return result
  }
  override fun toString(): String {
    return "PreloadResultMessage(ok=$ok, preloadMs=$preloadMs, errorCode=$errorCode)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlaybackStartedMessage (
  /** When the audio started, on the input clock (InputClockApi base). */
  val audioStartMonoUs: Long,
  /** iOS: `AVAudioSession.outputLatency`; Android: best estimate or 0. */
  val outputLatencyMs: Long,
  val outputRoute: OutputRouteMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaybackStartedMessage {
      val audioStartMonoUs = pigeonVar_list[0] as Long
      val outputLatencyMs = pigeonVar_list[1] as Long
      val outputRoute = pigeonVar_list[2] as OutputRouteMessage
      return PlaybackStartedMessage(audioStartMonoUs, outputLatencyMs, outputRoute)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      audioStartMonoUs,
      outputLatencyMs,
      outputRoute,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlaybackStartedMessage
    return ClipPlayerApiPigeonUtils.deepEquals(this.audioStartMonoUs, other.audioStartMonoUs) && ClipPlayerApiPigeonUtils.deepEquals(this.outputLatencyMs, other.outputLatencyMs) && ClipPlayerApiPigeonUtils.deepEquals(this.outputRoute, other.outputRoute)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ClipPlayerApiPigeonUtils.deepHash(this.audioStartMonoUs)
    result = 31 * result + ClipPlayerApiPigeonUtils.deepHash(this.outputLatencyMs)
    result = 31 * result + ClipPlayerApiPigeonUtils.deepHash(this.outputRoute)
    return result
  }
  override fun toString(): String {
    return "PlaybackStartedMessage(audioStartMonoUs=$audioStartMonoUs, outputLatencyMs=$outputLatencyMs, outputRoute=$outputRoute)"
  }
}
private open class ClipPlayerApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OutputRouteMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClipSourceMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreloadResultMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaybackStartedMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is OutputRouteMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ClipSourceMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PreloadResultMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PlaybackStartedMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ClipPlayerApi {
  /**
   * Downloads a clip into the app's temporary cache (`game.starting`
   * prefetch). Only called when the provider allows prefetching.
   */
  suspend fun prefetch(clipRef: String, clipUrl: String): PreloadResultMessage
  /**
   * Loads the clip, positions it at the snippet start and prepares the audio
   * output. Never produces sound.
   */
  suspend fun prepare(clip: ClipSourceMessage): PreloadResultMessage
  /**
   * Starts the prepared clip at [startAtMonoUs] on the input clock and
   * completes once playback has started. Plays at most the snippet.
   * iOS: `AVAudioPlayer.play(atTime:)` mapped through `deviceCurrentTime`.
   * Android: `Handler.postAtTime` on the uptime clock, then `play()`.
   */
  suspend fun playAt(startAtMonoUs: Long): PlaybackStartedMessage
  /** Stops playback and releases the prepared clip. */
  fun stop()
  /**
   * Releases the player and deletes every cached clip (licensing: clips are
   * kept only in memory or temporary cache for the duration of a game).
   */
  fun dispose()

  companion object {
    /** The codec used by ClipPlayerApi. */
    val codec: MessageCodec<Any?> by lazy {
      ClipPlayerApiPigeonCodec()
    }
    /** Sets up an instance of `ClipPlayerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ClipPlayerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sporand_native.ClipPlayerApi.prefetch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clipRefArg = args[0] as String
            val clipUrlArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.prefetch(clipRefArg, clipUrlArg))
              } catch (exception: Throwable) {
                ClipPlayerApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sporand_native.ClipPlayerApi.prepare$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clipArg = args[0] as ClipSourceMessage
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.prepare(clipArg))
              } catch (exception: Throwable) {
                ClipPlayerApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sporand_native.ClipPlayerApi.playAt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startAtMonoUsArg = args[0] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.playAt(startAtMonoUsArg))
              } catch (exception: Throwable) {
                ClipPlayerApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sporand_native.ClipPlayerApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              ClipPlayerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sporand_native.ClipPlayerApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              ClipPlayerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
