// Generated by Pigeon from apps/mobile/pigeons/. Do not edit by hand:
// run `dart run pigeon --input pigeons/<file>.dart` in apps/mobile instead.
// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// `round.playback_started.output_route`.
enum OutputRouteMessage {
  speaker,
  wired,
  bluetooth,
  airplay,
  other;
}

/// One snippet of a signed clip URL (`round.prepare.clip`).
class ClipSourceMessage {
  ClipSourceMessage({
    required this.clipUrl,
    this.clipRef,
    required this.snippetStartMs,
    required this.snippetDurationMs,
  });

  String clipUrl;

  /// Matches a `game.starting.prefetch[].clip_ref` already in the cache.
  String? clipRef;

  int snippetStartMs;

  int snippetDurationMs;

  List<Object?> _toList() {
    return <Object?>[
      clipUrl,
      clipRef,
      snippetStartMs,
      snippetDurationMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static ClipSourceMessage decode(Object result) {
    result as List<Object?>;
    return ClipSourceMessage(
      clipUrl: result[0]! as String,
      clipRef: result[1] as String?,
      snippetStartMs: result[2]! as int,
      snippetDurationMs: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ClipSourceMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(clipUrl, other.clipUrl) && _deepEquals(clipRef, other.clipRef) && _deepEquals(snippetStartMs, other.snippetStartMs) && _deepEquals(snippetDurationMs, other.snippetDurationMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ClipSourceMessage(clipUrl: $clipUrl, clipRef: $clipRef, snippetStartMs: $snippetStartMs, snippetDurationMs: $snippetDurationMs)';
  }
}

class PreloadResultMessage {
  PreloadResultMessage({
    required this.ok,
    required this.preloadMs,
    this.errorCode,
  });

  bool ok;

  int preloadMs;

  /// snake_case failure code for `round.playback_failed.reason`.
  String? errorCode;

  List<Object?> _toList() {
    return <Object?>[
      ok,
      preloadMs,
      errorCode,
    ];
  }

  Object encode() {
    return _toList();  }

  static PreloadResultMessage decode(Object result) {
    result as List<Object?>;
    return PreloadResultMessage(
      ok: result[0]! as bool,
      preloadMs: result[1]! as int,
      errorCode: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreloadResultMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ok, other.ok) && _deepEquals(preloadMs, other.preloadMs) && _deepEquals(errorCode, other.errorCode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PreloadResultMessage(ok: $ok, preloadMs: $preloadMs, errorCode: $errorCode)';
  }
}

class PlaybackStartedMessage {
  PlaybackStartedMessage({
    required this.audioStartMonoUs,
    required this.outputLatencyMs,
    required this.outputRoute,
  });

  /// When the audio started, on the input clock (InputClockApi base).
  int audioStartMonoUs;

  /// iOS: `AVAudioSession.outputLatency`; Android: best estimate or 0.
  int outputLatencyMs;

  OutputRouteMessage outputRoute;

  List<Object?> _toList() {
    return <Object?>[
      audioStartMonoUs,
      outputLatencyMs,
      outputRoute,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlaybackStartedMessage decode(Object result) {
    result as List<Object?>;
    return PlaybackStartedMessage(
      audioStartMonoUs: result[0]! as int,
      outputLatencyMs: result[1]! as int,
      outputRoute: result[2]! as OutputRouteMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlaybackStartedMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(audioStartMonoUs, other.audioStartMonoUs) && _deepEquals(outputLatencyMs, other.outputLatencyMs) && _deepEquals(outputRoute, other.outputRoute);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlaybackStartedMessage(audioStartMonoUs: $audioStartMonoUs, outputLatencyMs: $outputLatencyMs, outputRoute: $outputRoute)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is OutputRouteMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ClipSourceMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PreloadResultMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PlaybackStartedMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : OutputRouteMessage.values[value];
      case 130:
        return ClipSourceMessage.decode(readValue(buffer)!);
      case 131:
        return PreloadResultMessage.decode(readValue(buffer)!);
      case 132:
        return PlaybackStartedMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ClipPlayerApi {
  /// Constructor for [ClipPlayerApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ClipPlayerApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  /// Downloads a clip into the app's temporary cache (`game.starting`
  /// prefetch). Only called when the provider allows prefetching.
  Future<PreloadResultMessage> prefetch(String clipRef, String clipUrl) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sporand_native.ClipPlayerApi.prefetch$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[clipRef, clipUrl]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PreloadResultMessage;
  }

  /// Loads the clip, positions it at the snippet start and prepares the audio
  /// output. Never produces sound.
  Future<PreloadResultMessage> prepare(ClipSourceMessage clip) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sporand_native.ClipPlayerApi.prepare$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[clip]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PreloadResultMessage;
  }

  /// Starts the prepared clip at [startAtMonoUs] on the input clock and
  /// completes once playback has started. Plays at most the snippet.
  /// iOS: `AVAudioPlayer.play(atTime:)` mapped through `deviceCurrentTime`.
  /// Android: `Handler.postAtTime` on the uptime clock, then `play()`.
  Future<PlaybackStartedMessage> playAt(int startAtMonoUs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sporand_native.ClipPlayerApi.playAt$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startAtMonoUs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlaybackStartedMessage;
  }

  /// Stops playback and releases the prepared clip.
  Future<void> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sporand_native.ClipPlayerApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Releases the player and deletes every cached clip (licensing: clips are
  /// kept only in memory or temporary cache for the duration of a game).
  Future<void> dispose() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sporand_native.ClipPlayerApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
