/// Native bridges of the SpoRand app, generated by Pigeon from
/// `apps/mobile/pigeons/`. The app wraps them behind its own interfaces
/// (`InputClock`, `PlaybackAdapter`) so tests never touch a platform channel.
library;

export 'src/clip_player_api.g.dart';
export 'src/input_clock_api.g.dart';
