/// Native bridges of the SpoRand app, generated by Pigeon from
/// `pigeons/` (repository root). The app wraps them behind its own interfaces
/// (`PlaybackAdapter`, `MusicAppLauncher`) so tests never touch
/// a platform channel.
library;

export 'src/clip_player_api.g.dart';
export 'src/music_app_api.g.dart';
