// Generated by Pigeon from apps/mobile/pigeons/. Do not edit by hand:
// run `dart run pigeon --input pigeons/<file>.dart` in apps/mobile instead.
// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? NativeBridgeError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum ClipPlayerApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// `round.playback_started.output_route`.
enum OutputRouteMessage: Int, CaseIterable {
  case speaker = 0
  case wired = 1
  case bluetooth = 2
  case airplay = 3
  case other = 4
}

/// One snippet of a signed clip URL (`round.prepare.clip`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct ClipSourceMessage: Hashable, CustomStringConvertible {
  var clipUrl: String
  /// Matches a `game.starting.prefetch[].clip_ref` already in the cache.
  var clipRef: String? = nil
  var snippetStartMs: Int64
  var snippetDurationMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClipSourceMessage? {
    let clipUrl = pigeonVar_list[0] as! String
    let clipRef: String? = nilOrValue(pigeonVar_list[1])
    let snippetStartMs = pigeonVar_list[2] as! Int64
    let snippetDurationMs = pigeonVar_list[3] as! Int64

    return ClipSourceMessage(
      clipUrl: clipUrl,
      clipRef: clipRef,
      snippetStartMs: snippetStartMs,
      snippetDurationMs: snippetDurationMs
    )
  }
  func toList() -> [Any?] {
    return [
      clipUrl,
      clipRef,
      snippetStartMs,
      snippetDurationMs,
    ]
  }
  static func == (lhs: ClipSourceMessage, rhs: ClipSourceMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClipPlayerApiPigeonInternal.deepEquals(lhs.clipUrl, rhs.clipUrl) && ClipPlayerApiPigeonInternal.deepEquals(lhs.clipRef, rhs.clipRef) && ClipPlayerApiPigeonInternal.deepEquals(lhs.snippetStartMs, rhs.snippetStartMs) && ClipPlayerApiPigeonInternal.deepEquals(lhs.snippetDurationMs, rhs.snippetDurationMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClipSourceMessage")
    ClipPlayerApiPigeonInternal.deepHash(value: clipUrl, hasher: &hasher)
    ClipPlayerApiPigeonInternal.deepHash(value: clipRef, hasher: &hasher)
    ClipPlayerApiPigeonInternal.deepHash(value: snippetStartMs, hasher: &hasher)
    ClipPlayerApiPigeonInternal.deepHash(value: snippetDurationMs, hasher: &hasher)
  }

  public var description: String {
    return "ClipSourceMessage(clipUrl: \(String(describing: clipUrl)), clipRef: \(String(describing: clipRef)), snippetStartMs: \(String(describing: snippetStartMs)), snippetDurationMs: \(String(describing: snippetDurationMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PreloadResultMessage: Hashable, CustomStringConvertible {
  var ok: Bool
  var preloadMs: Int64
  /// snake_case failure code for `round.playback_failed.reason`.
  var errorCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PreloadResultMessage? {
    let ok = pigeonVar_list[0] as! Bool
    let preloadMs = pigeonVar_list[1] as! Int64
    let errorCode: String? = nilOrValue(pigeonVar_list[2])

    return PreloadResultMessage(
      ok: ok,
      preloadMs: preloadMs,
      errorCode: errorCode
    )
  }
  func toList() -> [Any?] {
    return [
      ok,
      preloadMs,
      errorCode,
    ]
  }
  static func == (lhs: PreloadResultMessage, rhs: PreloadResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClipPlayerApiPigeonInternal.deepEquals(lhs.ok, rhs.ok) && ClipPlayerApiPigeonInternal.deepEquals(lhs.preloadMs, rhs.preloadMs) && ClipPlayerApiPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PreloadResultMessage")
    ClipPlayerApiPigeonInternal.deepHash(value: ok, hasher: &hasher)
    ClipPlayerApiPigeonInternal.deepHash(value: preloadMs, hasher: &hasher)
    ClipPlayerApiPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
  }

  public var description: String {
    return "PreloadResultMessage(ok: \(String(describing: ok)), preloadMs: \(String(describing: preloadMs)), errorCode: \(String(describing: errorCode)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlaybackStartedMessage: Hashable, CustomStringConvertible {
  /// When the audio started: a raw OS input-clock value (InputClockApi
  /// base). Native code never knows the process anchor; the Dart side
  /// converts it with `InputClock.fromOsUs` (brief §5 "process anchor").
  var audioStartOsUs: Int64
  /// iOS: `AVAudioSession.outputLatency`; Android: best estimate or 0.
  var outputLatencyMs: Int64
  var outputRoute: OutputRouteMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlaybackStartedMessage? {
    let audioStartOsUs = pigeonVar_list[0] as! Int64
    let outputLatencyMs = pigeonVar_list[1] as! Int64
    let outputRoute = pigeonVar_list[2] as! OutputRouteMessage

    return PlaybackStartedMessage(
      audioStartOsUs: audioStartOsUs,
      outputLatencyMs: outputLatencyMs,
      outputRoute: outputRoute
    )
  }
  func toList() -> [Any?] {
    return [
      audioStartOsUs,
      outputLatencyMs,
      outputRoute,
    ]
  }
  static func == (lhs: PlaybackStartedMessage, rhs: PlaybackStartedMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ClipPlayerApiPigeonInternal.deepEquals(lhs.audioStartOsUs, rhs.audioStartOsUs) && ClipPlayerApiPigeonInternal.deepEquals(lhs.outputLatencyMs, rhs.outputLatencyMs) && ClipPlayerApiPigeonInternal.deepEquals(lhs.outputRoute, rhs.outputRoute)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlaybackStartedMessage")
    ClipPlayerApiPigeonInternal.deepHash(value: audioStartOsUs, hasher: &hasher)
    ClipPlayerApiPigeonInternal.deepHash(value: outputLatencyMs, hasher: &hasher)
    ClipPlayerApiPigeonInternal.deepHash(value: outputRoute, hasher: &hasher)
  }

  public var description: String {
    return "PlaybackStartedMessage(audioStartOsUs: \(String(describing: audioStartOsUs)), outputLatencyMs: \(String(describing: outputLatencyMs)), outputRoute: \(String(describing: outputRoute)))"
  }
}

private class ClipPlayerApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OutputRouteMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return ClipSourceMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return PreloadResultMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return PlaybackStartedMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ClipPlayerApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? OutputRouteMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ClipSourceMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PreloadResultMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PlaybackStartedMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ClipPlayerApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ClipPlayerApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ClipPlayerApiPigeonCodecWriter(data: data)
  }
}

class ClipPlayerApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ClipPlayerApiPigeonCodec(readerWriter: ClipPlayerApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ClipPlayerApi {
  /// Downloads a clip into the app's temporary cache (`game.starting`
  /// prefetch). Only called when the provider allows prefetching.
  func prefetch(clipRef: String, clipUrl: String) async throws -> PreloadResultMessage
  /// Loads the clip, positions it at the snippet start and prepares the audio
  /// output. Never produces sound.
  func prepare(clip: ClipSourceMessage) async throws -> PreloadResultMessage
  /// Starts the prepared clip at [startAtOsUs] (raw OS input clock; the Dart
  /// side adds the process anchor with `InputClock.toOsUs`) and completes
  /// once playback has started. Plays at most the snippet.
  /// iOS: `AVAudioPlayer.play(atTime:)` mapped through `deviceCurrentTime`.
  /// Android: `Handler.postAtTime` on the uptime clock, then `play()`.
  func playAt(startAtOsUs: Int64) async throws -> PlaybackStartedMessage
  /// Stops playback and releases the prepared clip.
  func stop() throws
  /// Releases the player and deletes every cached clip (licensing: clips are
  /// kept only in memory or temporary cache for the duration of a game).
  func dispose() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ClipPlayerApiSetup {
  static var codec: FlutterStandardMessageCodec { ClipPlayerApiPigeonCodec.shared }
  /// Sets up an instance of `ClipPlayerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ClipPlayerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Downloads a clip into the app's temporary cache (`game.starting`
    /// prefetch). Only called when the provider allows prefetching.
    let prefetchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporand_native.ClipPlayerApi.prefetch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prefetchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clipRefArg = args[0] as! String
        let clipUrlArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.prefetch(clipRef: clipRefArg, clipUrl: clipUrlArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      prefetchChannel.setMessageHandler(nil)
    }
    /// Loads the clip, positions it at the snippet start and prepares the audio
    /// output. Never produces sound.
    let prepareChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporand_native.ClipPlayerApi.prepare\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepareChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clipArg = args[0] as! ClipSourceMessage
        Task { @MainActor in
          do {
            let result = try await api.prepare(clip: clipArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      prepareChannel.setMessageHandler(nil)
    }
    /// Starts the prepared clip at [startAtOsUs] (raw OS input clock; the Dart
    /// side adds the process anchor with `InputClock.toOsUs`) and completes
    /// once playback has started. Plays at most the snippet.
    /// iOS: `AVAudioPlayer.play(atTime:)` mapped through `deviceCurrentTime`.
    /// Android: `Handler.postAtTime` on the uptime clock, then `play()`.
    let playAtChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporand_native.ClipPlayerApi.playAt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playAtChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let startAtOsUsArg = args[0] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.playAt(startAtOsUs: startAtOsUsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      playAtChannel.setMessageHandler(nil)
    }
    /// Stops playback and releases the prepared clip.
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporand_native.ClipPlayerApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Releases the player and deletes every cached clip (licensing: clips are
    /// kept only in memory or temporary cache for the duration of a game).
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporand_native.ClipPlayerApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
