// Generated by Pigeon from apps/mobile/pigeons/. Do not edit by hand:
// run `dart run pigeon --input pigeons/<file>.dart` in apps/mobile instead.
// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class NativeBridgeError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "NativeBridgeError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? NativeBridgeError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum InputClockApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class InputClockApiPigeonCodecReader: FlutterStandardReader {
}

private class InputClockApiPigeonCodecWriter: FlutterStandardWriter {
}

private class InputClockApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return InputClockApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return InputClockApiPigeonCodecWriter(data: data)
  }
}

class InputClockApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = InputClockApiPigeonCodec(readerWriter: InputClockApiPigeonCodecReaderWriter())
}

/// The OS input clock: the clock that stamps touch events.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol InputClockApi {
  /// Microseconds on the device input clock: a raw OS value (`os_us`).
  ///
  /// Never sent off-device (Apple required-reason API 35F9.1): the Dart
  /// `InputClock` subtracts the process anchor before any value reaches the
  /// protocol (brief §5 "process anchor").
  ///
  /// - iOS: `ProcessInfo.processInfo.systemUptime * 1e6`, the base of
  ///   `UITouch.timestamp` (stops while the device sleeps).
  /// - Android: `SystemClock.uptimeMillis() * 1000`, the base of
  ///   `MotionEvent.getEventTime()` (1 ms precision).
  func nowMicros() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class InputClockApiSetup {
  static var codec: FlutterStandardMessageCodec { InputClockApiPigeonCodec.shared }
  /// Sets up an instance of `InputClockApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: InputClockApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Microseconds on the device input clock: a raw OS value (`os_us`).
    ///
    /// Never sent off-device (Apple required-reason API 35F9.1): the Dart
    /// `InputClock` subtracts the process anchor before any value reaches the
    /// protocol (brief §5 "process anchor").
    ///
    /// - iOS: `ProcessInfo.processInfo.systemUptime * 1e6`, the base of
    ///   `UITouch.timestamp` (stops while the device sleeps).
    /// - Android: `SystemClock.uptimeMillis() * 1000`, the base of
    ///   `MotionEvent.getEventTime()` (1 ms precision).
    let nowMicrosChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporand_native.InputClockApi.nowMicros\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      nowMicrosChannel.setMessageHandler { _, reply in
        do {
          let result = try api.nowMicros()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      nowMicrosChannel.setMessageHandler(nil)
    }
  }
}
