// Generated by Pigeon from pigeons/. Do not edit by hand:
// run `dart run pigeon --input pigeons/<file>.dart` at the repository root instead.
// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? NativeBridgeError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MusicAppApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// The song of `round.prepare.cue` as a system media search.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MusicSearchMessage: Hashable, CustomStringConvertible {
  var title: String
  /// The first credited artist.
  var artist: String
  /// Free-text search, e.g. "Northern Lights Test Artist".
  var query: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MusicSearchMessage? {
    let title = pigeonVar_list[0] as! String
    let artist = pigeonVar_list[1] as! String
    let query = pigeonVar_list[2] as! String

    return MusicSearchMessage(
      title: title,
      artist: artist,
      query: query
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      artist,
      query,
    ]
  }
  static func == (lhs: MusicSearchMessage, rhs: MusicSearchMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MusicAppApiPigeonInternal.deepEquals(lhs.title, rhs.title) && MusicAppApiPigeonInternal.deepEquals(lhs.artist, rhs.artist) && MusicAppApiPigeonInternal.deepEquals(lhs.query, rhs.query)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MusicSearchMessage")
    MusicAppApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    MusicAppApiPigeonInternal.deepHash(value: artist, hasher: &hasher)
    MusicAppApiPigeonInternal.deepHash(value: query, hasher: &hasher)
  }

  public var description: String {
    return "MusicSearchMessage(title: \(String(describing: title)), artist: \(String(describing: artist)), query: \(String(describing: query)))"
  }
}

private class MusicAppApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MusicSearchMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MusicAppApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MusicSearchMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MusicAppApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MusicAppApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MusicAppApiPigeonCodecWriter(data: data)
  }
}

class MusicAppApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MusicAppApiPigeonCodec(readerWriter: MusicAppApiPigeonCodecReaderWriter())
}

/// [новое имя — согласовать] `MusicAppApi`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MusicAppApi {
  /// Android: starts `MediaStore.INTENT_ACTION_MEDIA_PLAY_FROM_SEARCH` with
  /// `EXTRA_MEDIA_FOCUS` = audio (`Audio.Media.ENTRY_CONTENT_TYPE`),
  /// `EXTRA_MEDIA_TITLE`, `EXTRA_MEDIA_ARTIST` and `SearchManager.QUERY`.
  /// Returns false when no installed app handles it.
  ///
  /// iOS has no equivalent system intent: always false; the Dart side opens
  /// the cue's `hint_url` instead.
  func playFromSearch(search: MusicSearchMessage) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MusicAppApiSetup {
  static var codec: FlutterStandardMessageCodec { MusicAppApiPigeonCodec.shared }
  /// Sets up an instance of `MusicAppApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MusicAppApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Android: starts `MediaStore.INTENT_ACTION_MEDIA_PLAY_FROM_SEARCH` with
    /// `EXTRA_MEDIA_FOCUS` = audio (`Audio.Media.ENTRY_CONTENT_TYPE`),
    /// `EXTRA_MEDIA_TITLE`, `EXTRA_MEDIA_ARTIST` and `SearchManager.QUERY`.
    /// Returns false when no installed app handles it.
    ///
    /// iOS has no equivalent system intent: always false; the Dart side opens
    /// the cue's `hint_url` instead.
    let playFromSearchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sporand_native.MusicAppApi.playFromSearch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playFromSearchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let searchArg = args[0] as! MusicSearchMessage
        do {
          let result = try api.playFromSearch(search: searchArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playFromSearchChannel.setMessageHandler(nil)
    }
  }
}
